name: Update Places JSON from Airtable

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Airtable data
        env:
          AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
        run: |
          python fetch_airtable.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add places.json
          git commit -m "Update places.json from Airtable" || echo "No changes to commit"
          git push
